version: "3.9"

services:
  goprint:
    image: sast/sast-goprint:current
    container_name: sast-goprint
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
