// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: office_converter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 文件转换请求
type ConversionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceFilePath string                 `protobuf:"bytes,1,opt,name=source_file_path,json=sourceFilePath,proto3" json:"source_file_path,omitempty"` // 源文件路径（绝对路径）
	TargetFormat   string                 `protobuf:"bytes,2,opt,name=target_format,json=targetFormat,proto3" json:"target_format,omitempty"`         // 目标格式（必须为 "pdf"）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversionRequest) Reset() {
	*x = ConversionRequest{}
	mi := &file_office_converter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversionRequest) ProtoMessage() {}

func (x *ConversionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_office_converter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversionRequest.ProtoReflect.Descriptor instead.
func (*ConversionRequest) Descriptor() ([]byte, []int) {
	return file_office_converter_proto_rawDescGZIP(), []int{0}
}

func (x *ConversionRequest) GetSourceFilePath() string {
	if x != nil {
		return x.SourceFilePath
	}
	return ""
}

func (x *ConversionRequest) GetTargetFormat() string {
	if x != nil {
		return x.TargetFormat
	}
	return ""
}

// 文件转换响应
type ConversionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                      // 是否成功
	OutputFilePath string                 `protobuf:"bytes,2,opt,name=output_file_path,json=outputFilePath,proto3" json:"output_file_path,omitempty"` // 输出文件路径（成功时有效）
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`         // 错误信息（失败时有效）
	ErrorCode      string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`                  // 错误代码
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversionResponse) Reset() {
	*x = ConversionResponse{}
	mi := &file_office_converter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversionResponse) ProtoMessage() {}

func (x *ConversionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_office_converter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversionResponse.ProtoReflect.Descriptor instead.
func (*ConversionResponse) Descriptor() ([]byte, []int) {
	return file_office_converter_proto_rawDescGZIP(), []int{1}
}

func (x *ConversionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConversionResponse) GetOutputFilePath() string {
	if x != nil {
		return x.OutputFilePath
	}
	return ""
}

func (x *ConversionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConversionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_office_converter_proto protoreflect.FileDescriptor

const file_office_converter_proto_rawDesc = "" +
	"\n" +
	"\x16office_converter.proto\x12\x10office_converter\"b\n" +
	"\x11ConversionRequest\x12(\n" +
	"\x10source_file_path\x18\x01 \x01(\tR\x0esourceFilePath\x12#\n" +
	"\rtarget_format\x18\x02 \x01(\tR\ftargetFormat\"\x9c\x01\n" +
	"\x12ConversionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x10output_file_path\x18\x02 \x01(\tR\x0eoutputFilePath\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode2s\n" +
	"\x16OfficeConverterService\x12Y\n" +
	"\fConvertToPdf\x12#.office_converter.ConversionRequest\x1a$.office_converter.ConversionResponseB\x12P\x01Z\x0egoprint/api/pbb\x06proto3"

var (
	file_office_converter_proto_rawDescOnce sync.Once
	file_office_converter_proto_rawDescData []byte
)

func file_office_converter_proto_rawDescGZIP() []byte {
	file_office_converter_proto_rawDescOnce.Do(func() {
		file_office_converter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_office_converter_proto_rawDesc), len(file_office_converter_proto_rawDesc)))
	})
	return file_office_converter_proto_rawDescData
}

var file_office_converter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_office_converter_proto_goTypes = []any{
	(*ConversionRequest)(nil),  // 0: office_converter.ConversionRequest
	(*ConversionResponse)(nil), // 1: office_converter.ConversionResponse
}
var file_office_converter_proto_depIdxs = []int32{
	0, // 0: office_converter.OfficeConverterService.ConvertToPdf:input_type -> office_converter.ConversionRequest
	1, // 1: office_converter.OfficeConverterService.ConvertToPdf:output_type -> office_converter.ConversionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_office_converter_proto_init() }
func file_office_converter_proto_init() {
	if File_office_converter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_office_converter_proto_rawDesc), len(file_office_converter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_office_converter_proto_goTypes,
		DependencyIndexes: file_office_converter_proto_depIdxs,
		MessageInfos:      file_office_converter_proto_msgTypes,
	}.Build()
	File_office_converter_proto = out.File
	file_office_converter_proto_goTypes = nil
	file_office_converter_proto_depIdxs = nil
}
