// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: office_converter.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OfficeConverterService_ConvertToPdf_FullMethodName = "/office_converter.OfficeConverterService/ConvertToPdf"
)

// OfficeConverterServiceClient is the client API for OfficeConverterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 服务定义
type OfficeConverterServiceClient interface {
	// 转换单个Office文件到PDF
	ConvertToPdf(ctx context.Context, in *ConversionRequest, opts ...grpc.CallOption) (*ConversionResponse, error)
}

type officeConverterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOfficeConverterServiceClient(cc grpc.ClientConnInterface) OfficeConverterServiceClient {
	return &officeConverterServiceClient{cc}
}

func (c *officeConverterServiceClient) ConvertToPdf(ctx context.Context, in *ConversionRequest, opts ...grpc.CallOption) (*ConversionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConversionResponse)
	err := c.cc.Invoke(ctx, OfficeConverterService_ConvertToPdf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfficeConverterServiceServer is the server API for OfficeConverterService service.
// All implementations must embed UnimplementedOfficeConverterServiceServer
// for forward compatibility.
//
// 服务定义
type OfficeConverterServiceServer interface {
	// 转换单个Office文件到PDF
	ConvertToPdf(context.Context, *ConversionRequest) (*ConversionResponse, error)
	mustEmbedUnimplementedOfficeConverterServiceServer()
}

// UnimplementedOfficeConverterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOfficeConverterServiceServer struct{}

func (UnimplementedOfficeConverterServiceServer) ConvertToPdf(context.Context, *ConversionRequest) (*ConversionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertToPdf not implemented")
}
func (UnimplementedOfficeConverterServiceServer) mustEmbedUnimplementedOfficeConverterServiceServer() {
}
func (UnimplementedOfficeConverterServiceServer) testEmbeddedByValue() {}

// UnsafeOfficeConverterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfficeConverterServiceServer will
// result in compilation errors.
type UnsafeOfficeConverterServiceServer interface {
	mustEmbedUnimplementedOfficeConverterServiceServer()
}

func RegisterOfficeConverterServiceServer(s grpc.ServiceRegistrar, srv OfficeConverterServiceServer) {
	// If the following call panics, it indicates UnimplementedOfficeConverterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OfficeConverterService_ServiceDesc, srv)
}

func _OfficeConverterService_ConvertToPdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeConverterServiceServer).ConvertToPdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfficeConverterService_ConvertToPdf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeConverterServiceServer).ConvertToPdf(ctx, req.(*ConversionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OfficeConverterService_ServiceDesc is the grpc.ServiceDesc for OfficeConverterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OfficeConverterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "office_converter.OfficeConverterService",
	HandlerType: (*OfficeConverterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertToPdf",
			Handler:    _OfficeConverterService_ConvertToPdf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "office_converter.proto",
}
