# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import office_converter_pb2 as office__converter__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in office_converter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OfficeConverterServiceStub(object):
    """服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertToPdf = channel.unary_unary(
                '/office_converter.OfficeConverterService/ConvertToPdf',
                request_serializer=office__converter__pb2.ConversionRequest.SerializeToString,
                response_deserializer=office__converter__pb2.ConversionResponse.FromString,
                _registered_method=True)


class OfficeConverterServiceServicer(object):
    """服务定义
    """

    def ConvertToPdf(self, request, context):
        """转换单个Office文件到PDF
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OfficeConverterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertToPdf': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertToPdf,
                    request_deserializer=office__converter__pb2.ConversionRequest.FromString,
                    response_serializer=office__converter__pb2.ConversionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'office_converter.OfficeConverterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('office_converter.OfficeConverterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OfficeConverterService(object):
    """服务定义
    """

    @staticmethod
    def ConvertToPdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/office_converter.OfficeConverterService/ConvertToPdf',
            office__converter__pb2.ConversionRequest.SerializeToString,
            office__converter__pb2.ConversionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
