# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: office_converter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'office_converter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16office_converter.proto\x12\x10office_converter\"D\n\x11\x43onversionRequest\x12\x18\n\x10source_file_path\x18\x01 \x01(\t\x12\x15\n\rtarget_format\x18\x02 \x01(\t\"j\n\x12\x43onversionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x18\n\x10output_file_path\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x12\n\nerror_code\x18\x04 \x01(\t2s\n\x16OfficeConverterService\x12Y\n\x0c\x43onvertToPdf\x12#.office_converter.ConversionRequest\x1a$.office_converter.ConversionResponseB\x15P\x01Z\x11goprint/api/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'office_converter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001Z\021goprint/api/pb;pb'
  _globals['_CONVERSIONREQUEST']._serialized_start=44
  _globals['_CONVERSIONREQUEST']._serialized_end=112
  _globals['_CONVERSIONRESPONSE']._serialized_start=114
  _globals['_CONVERSIONRESPONSE']._serialized_end=220
  _globals['_OFFICECONVERTERSERVICE']._serialized_start=222
  _globals['_OFFICECONVERTERSERVICE']._serialized_end=337
# @@protoc_insertion_point(module_scope)
